### ISSUE TITLE
Update to Kotlin 1.4

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#108]
A new version of Kotlin is out: https://kotlinlang.org/docs/reference/whatsnew14.html

Let's use it! :)

**Comment by Loomie** [comment]
Kotest supports Kotlin 1.4 since 4.2.0. But that contains breaking changes in the modules: https://kotest.io/changelog/

Also Coroutines changed its "publication scheme" since 1.3.9 which support Kotlin 1.4: https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.9

**Comment by Loomie** [comment]
Done and builds.
