### ISSUE TITLE
Unit based combat

### ISSUE THREAD

**Issue by Loomie** [Baret/pltcmd#112]
**Basic idea/big picture**
The fighting of two elements should depend on their units. Each unit should attack another unit of the other element. Each unit needs combat statistics that describe how well it can fight.

**Details**
The combat should resolve shots for each unit of an element. Each shot has a chance to hit which is determined by the accuracy of the weapon. Over the time of a single tick (one minute) multiple shots can be made so the shots per minute are important.

**Technical background**
The attack statistics can be put into a weapon class. So the same type of attack can be used by different types of units. 

**Related issues/Prerequisites**
Based on #79

**Comment by Loomie** [comment]
Interessting read: [Probability of kill](https://en.wikipedia.org/wiki/Probability_of_kill)
> Additional factors include probability of a hit (Phit), probability of detection (Pd), reliability of the targeting system (Rsys), and reliability of the weapon (Rw), to name a few.

But those factors may be for additional refinements.

**Comment by Baret** [comment]
As you mentioned that one tick is one minute, remember that there is now: https://www.github.com/Baret/pltcmd/tree/master/game%2Foptions%2Fsrc%2Fmain%2Fkotlin%2Fde%2Fgleex%2Fpltcmd%2Fgame%2Foptions%2FGameConstants.kt ;)

**Comment by Loomie** [comment]
To begin with I only added some basic weapons. Special weapons like mortar is still missing. Also a grenade launcher is not yet implemented and I didn't found data of a 40mm IFV gun.

The implemented system is still very basic. The accuracy of a weapon is given for a specific range which has to be added. For ranged attacks issue #113 exists.
