### ISSUE TITLE
Map generator(s)

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#13]
**Basic idea/big picture**
There should be a way to generate parts of the world map. The world map will be devided into _Sectors_. A sector is 50 by 50 tiles big. New sectors will be generated on the fly, so a map generator should at least be able to generate those 50*50 tiles.

**Details**
There should be different implementations of map generators to see what feels best. Or to choose a different generator for each sector. Some implementation suggestions are:
- Mountaintop(s): give the generator one or more positions of "mountain tops" (highest possible terrain height). The generator goes "downhill" from there in every direction. Every neighboring tile is even or lower, depending on a random value.
- BottomUp: The same as Mountaintop, but starting with the lowest terrain height.
- AllPlain: It gets a terrrain height and type and makes all tiles the same. A simlpe first implementation and maybe useful for debugging/testing
- AllRandom: Well, what it says on the box
- Smoothing: Running a different generator, for example the AllRandom, and then smooth the map a bit.

**Technical background**
As my first ideas are mostly based on height map generation, maybe it would be a good idea to split map generators into two parts. First a HeightMapGenerator is being run, setting only the TerrainHeight at all the tiles. After that a TerrainMapGenerator is called, putting the TerrainType on top of it. That way a more realistic vegetation might be achieved, like flowing rivers, mountains not lower than a specific TerrainHeight and so on.

**Related issues/Prerequisites**
At least #14 has to be done.

**Comment by Loomie** [comment]
Created branch and pull request #32 for the implementation.

**Comment by Loomie** [comment]
> AllRandom: Well, what it says on the box

Done

**Comment by Baret** [comment]
I merged the branch now as the current map is "good enough". Improvements to map generaion will be done in further issues (which I will create soon).
