### ISSUE TITLE
React to contact

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#130]
When an element has visually detected "something" (another element, a base, something that lies around in the world) it needs to react to it.

The complete process of "seeing something and reacting to it" looks more or less like this:
```
1. See it
2. determine how well you see it
3. identify as much as possible
4. Act appropriately
```

## 1. See it

This is already done with #81. This is basically just "something is inside the visual range".

**This step is handled by a behavior** (currently called `LookingAround`).

## 2. determine how well you see it

The second step is technically closely coupled to the first one. It is also done with #81 and is the result of calculating a visual signal at the target's location. The result of this step is "a value between 0.0 and 1.0" (the `SignalStrength`).

**This step is handled by a facet**. It is called by `LookingAround` and currently called `Detects`.

## 3. identify as much as possible

Depending on how well the target is visible more or less details can be identified. These details may be composed of these (and more) questions:
- _What_ is it actually? Tank wrecks, Supply crates, an enemy element, etc?
- Depending on what it is we can make out further details. The most interesting (and probably complex) thing are enemy elements. They can reveal those bits of information:
  - What affiliation? (friendly, hostile, allied, unknown)
  - direction/location: Where is the contact?
  - Element size?
  - Element type?
  - More details of the element composition? -> Is it light infantry or do they have heavy weaponry like AT, HMG.

All those potentially unknown bits of information form a `Contact`. There will most probably be a class to carry all that information (or non-information :D ). Contacts should also be held in an attribute of _known contacts_ so that an element will not react to something every single tick again and again. Only if something changes (i.e. can be seen better) another reaction may be needed.

**This step is also handled by `Detects`**. The resulting `Contact` should then be passed up the the "brain/element leader" to determine what needs to be done. Actually simply something like `currentGoal.butNow(HandleContact(newContact))`

## 4. Act appropriately

This step requires some intelligence/AI and must thus be handled by a `Goal`. Depending on what the element was currently doing there are lots of things that may happen:
- Simply ignore the contact because it is not relevant
- Do a contact report
- Directly engage the enemy
- Change the current direction of movement or halt altogether to avoid contact
- ...

**This step needs to be handled by goals**.

**Comment by Loomie** [comment]
> 3. identify as much as possible

I think for different kinds of information different facets should be used. So one `DetectEntities` command can be handled by different facets each gathering other informations and reactions from that. There can be a `ReportContacts` facet that tells the command what is going on. There could be a `CollectStuff` facet that moves to collectable things that are in reach and so on.

> 4. Act appropriately
The detection facet should create commands for facets that act on the detected information. Like a `EnemyContact` command which may be handled by a facet that reports contact to the hq and another facet that enganges the enemy.
