### ISSUE TITLE
Create the world

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#14]
**Basic idea/big picture**
There needs to be a "world" containing all map tiles. There should be a way to access them in the form of _Sectors_ (see below).
Later the world will also hold all Elements (and other game entities) moving around. Probably this will be one part of a _Game_ class, that might hold additional state regarding the player.

**Details**
The world map consists of sectors. Each sector has 50 by 50 tiles. A Tile has a coordinate, for examlpe (577|488). The last two digits are the coordinates inside of sector (**5**[5x]|**4**[5x]). This means that two sectors make up a "big" coordinate (one sector from 500|400 to 549|400 and the next one from 550|400 to 599|400). But that could be used to display a world map, kind of "zooming out" of the default play view. I don't know if this will be needed though.
**For now it is enough to fill up the map with a default tile, representing a default TerrainHeight and TerrainType!** 

**Technical background**
Model:
I am not sure if the world map needs a map of sectors and each sector needs a map of tiles. Maybe it is enough to save _all_ the tiles in the world and just display 50 by 50 chunks of it. Or differently speaking: Just scroll the visible part of the map by 50 tiles. This could also make map generation (#13) easier.

UI:
The map should already be visible in the gameArea including some kind of border/decoration showing the coordinates. The "main coordinates" or "sector coordinates" should be highlighted. And there should be markings every 10 and 5 tiles, like shown [in the mockup](https://github.com/Baret/pltcmd/blob/master/mockups/mapview.png)

**Comment by Loomie** [comment]
The model exists in a branch. The UI is to be done.

**Comment by Baret** [comment]
For simplicity: this branch https://github.com/Baret/pltcmd/tree/Issue_14_Create_The_World

**Comment by Loomie** [comment]
Pull request #17
