### ISSUE TITLE
Basic system for GameEntities (aka "use amethyst")

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#19]
**Basic idea/big picture**
Now that there is a world and it can be displayed, it is time to introduce [Amethyst](https://github.com/hexworks/amethyst).

**Details**
As this issue should only create the very basic system for future game mechanics, it is enough to have a _game_ that contains an _engine_ and puts one unit somewhere on the map and displays it.

**Technical background**
Basics on how to implements `Entity`s, their `Attribute`s and `System`s to handle them can be [found here](https://hexworks.org/posts/tutorials/2019/02/13/how-to-make-a-roguelike-the-player.html).

**Related issues/Prerequisites**
#14 should be done and in the master before starting.

**Comment by Loomie** [comment]
Implemented the following in #58:
> Elements with a position are now entities. They can move to a destination by a behaviour. The destination is set by a command and executed in a facet. All entities are updated by the `GameEngine` that is triggered every second in the main.
