### ISSUE TITLE
Create a basic model for units

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#2]
We need a model to represent the hierarchy of military units to some degree.
The rough idea so far is something like:
There are `Elements` and `Units`. There might be `Units` of types
- Soldier
- Helicopter
- APC
And they make up different kind of `Elements` while `Elements` themselves can again make up bigger `Elements`. For example
- 2 Soldiers (`Unit`) are a Buddyteam (`Element`)
- 2 Buddyteams are a Fireteam (`Element`)
- 2 Fireteams are a Squad (`Element`)
- etc...

For the beginning maybe a simple structure of `Platoon` consisting of `Soldier`s might be enough.

**Comment by Loomie** [comment]
While looking for some names of elements I [found in Wikipedia](https://en.wikipedia.org/wiki/Military_unit#Commands,_formations,_and_units) "[...] the building blocks of a military as commands, formations, and units.". So the elements are named formations and the commands are missing in the inital idea. A command may be the scope of this game as "[...] it is an administrative and executive strategic headquarters [...]".

Now I have to filter...

**Comment by Baret** [comment]
Interesting to read. The current model already looks promising, but I might have some comments. Could you open a pull request so we can discuss detils directly at the code, @Loomie ?

**Comment by Loomie** [comment]
see #6

**Comment by Loomie** [comment]
How about the current state of the pull request?
