### ISSUE TITLE
Additional map decoration

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#20]
The first "layer" of decoration around the map view is already there but the second one, showing the Coordinates and highlighting the MainCoordinates is still missing. [The mockup](https://raw.githubusercontent.com/Baret/pltcmd/master/mockups/mapview.png) shows how it might look like. But maybe it is better to center the coordinate values.

**Comment by Loomie** [comment]
The decoration exists now (see #23), but it starts directly at the grid. In the mockup it was centered. That still has to be done.

**Comment by Loomie** [comment]
Polishing is done. Pull request #23 is ready for review.

**Comment by Baret** [comment]
I really like it the way it looks now. Different colors for X and Y main coordinate and centering it above the + highlight is much better than the mockup 👍
