### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by Loomie** [Baret/pltcmd#24]
**Basic idea/big picture**
An image that identifies this project at first glance. It should be used everywhere the the project name is shown.

**Details**
On a screenshot I saw that the application window uses the default Java icon. That should be replaced with an own application symbol. Such an image can also be used on the GitHub project.

It should be reasoable large (like 256x256) to be able to scale down for different purposes. The image must iconify the idea of the game. For small areas like the application icon it must be readable at low resolutions like 24x24 pixels.

**Technical background**
Maybe a single image format is not enough, but PNG is widely accepted and supports all commons (raster) image features (like transparency). For editing a layered format may be better or a vector graphics like SVG should be used if the content fits.

**Related issues/Prerequisites**
In #12 the README will be filled. This logo should also appear there.

**Comment by Baret** [comment]
Great idea! But I would rather call it an "icon". I was already thinking about a logo showing up when the game starts (like a classic intro Logo/Animation). But probably that would just be a large version of the logo you suppose (or the other way around).
