### ISSUE TITLE
Bug: Map grid and coordinates are relative to drawing not model

### ISSUE THREAD

**Issue by Loomie** [Baret/pltcmd#28]
**Description**
The markers are at the first tile of the visible area. But they should be aligned to a full 50th of the grid. Currently the top left ist 249|350 because the bottom left (origin of the map) is 200|350.

**Location**
`MapCoordinates` and `MapGrid`

**Reproduction**
Just start the main application after #22 is fixed.

**Comment by Baret** [comment]
Currently there are also decorations "outside" the 50 tiles of the map:
- The gridhighlights (+) are printed on the 51st tile, which makes the corners look awkward
- The last coordinate is partially visible

These issues should also be fixed here to make the map decorations prettier.

**Comment by Loomie** [comment]
Done. See #33
