### ISSUE TITLE
Bug: Fix memory usage of RiverTyper

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#50]
**Description**
The intermediate genreator `RiverTyper` runs into heap space errors for most map seeds. The reason is the implementation of the underlying [DijkstraMap](http://www.roguebasin.com/index.php?title=Dijkstra_Maps_Visualized).

**Location**
The current implementation used is `de.gleex.pltcmd.mapping.dijkstra.DijkstraMap`. But that one is specialized for usage in the `MountainTopHeightMapper` and obviously not very memory efficient. There already is a skeleton implementation for a more generic dijkstra map called `DijkstraMapOfCoordinates`. This issue should be used to finish the implementation and create useful builders/factory methods to create instances, for example:
- The use case of the `MountainTopHeightMapper`: You do not know what `Coordinates` will be in the map so the builder holds a mutable state and you can set every coordinate with its according "cost value"
- `createMap(maxValue: Int, vararg targets: Coordinate)`: The targets are put into the initial map with value 0. Every `Coordinate` around the targets get the next higher value, so 1, and so on until the `maxValue` is reached.
- There might be similar methods possible with advanced options:
  - You also give it a `CoordinateArea` to limit the overall size of the map (i.e. if you want to create a dijkstra map for a single sector or other rectangle)
  - You give it a lambda to calculate the value for each coordinate. This might be useful later to take terrain into account to calculate the values of a tile.
- `convertMap(map: DijkstraMapOfCoordinates, valueToSetAsTarget: Int, targetValue: Int = 0)`: Convert an existing map setting all fields with value `valueToSetAsTarget` to `targetValue` which is 0 by default.

**Important**, as the comment in the class already states: It should be possible to easily abstract it later so you can also use `Block`s or `Tile`s as underlying data structure. Or to get all 8 neighbors of a `Coordinate` instad of 4 to allow diagonal movement. IMO all it takes would be to have a method that gets the neighbors of a tile in the map.

**Comment by Loomie** [comment]
Fixed the endless loop in #52

**Comment by Baret** [comment]
As the core problem has been fixed I created #53 for the implementation of the new dijkstra map.
