### ISSUE TITLE
Implement Faction

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#62]
**Basic idea/big picture**
The player (and in the future other players or AI enemies) controls a `Faction`. It contains everything that belongs to one army. At least:
- An HQ with a fixed position
- All elements
- much more that may be left out for now
  - For example (just to have it written down already)
  - Fog of War or rather "Known terrain". Needed by the map view to know what to show at each tile
  - Relations to other factions
  - Knowledge of the faction that is inherited by elements that leave the base, see #104 

**Details**
I am not sure if `Faction` will be an `Entity` of its own or just an `Attribute` of all entities affiliated with a faction. Maybe the overarching entity will be the `Army` having attributes like `faction`, `relations` (to other factions), `elements`, `hq` and so on...

**Comment by Loomie** [comment]
The base for the use of factions is done. It can be set as `Attribute` for an entity.

>  It contains everything that belongs to one army.

That has to be added in future issues. Maybe in the mentioned form:

> Maybe the overarching entity will be the `Army` having attributes like `faction`, `relations` (to other factions), `elements`, `hq` and so on...
