### ISSUE TITLE
Impement Radionet

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#63]
**Basic idea/big picture**
The backbone of an army is its radio net. All comms are sent as `Transmission`s (the model should be used here). This issue should lay the basics for the radio system implenented with Amethyst.

**Details**
Every faction should have its own radio net, possibly with multiple channels later. There needs to be a mechanism to "send a transmission out into 'the air'" to be received by all elements in range. The `RadioCommunicator` (and the corresponding example) already has the basics for such mechanics. Maybe these need to be moved directly into the engine (i.e. into a `System`).

**Technical background**
There will be the need to calculate paths between elements or at least to get the terrain along a line just like in the `RadioSignalFragment` and the `RadioSignalVisualizer`. This means, when not yet happened, the `GameContext` should be changed to have the `GameWorld` instead of the `WorldMap`.

**Related issues/Prerequisites**
A `Faction` (or `Army`?) should be present to contain the radio net. So issue #62 should be done first.

**Comment by Loomie** [comment]
I implemented my idea of radio transmissions. Now after some work it is not quiete the "basic idea" as it currently is not implemented with Amethyst. But the details are contained.

> There needs to be a mechanism to "send a transmission out into 'the air'" to be received by all elements in range. 
I used the EventBus for that. The sender has a maximum reach and each receiver has to check if he is inside that range. Then the receiver calculates the SignalStrength to check if anything reached him.

> There will be the need to calculate paths between elements or at least to get the terrain along a line  [...]
I implemented a line algorithm for path finding and applied it to the map to find the terrain.

Currently only the conversationExample uses the RadioCommunicator. Should it be used in or converted to an entity in this issue or another one?
