### ISSUE TITLE
Bug: Worlds with origin != (000|000) are impossible

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#69]
**Description**
When setting the world's origin to a value other than 0|0 the GeneratingView as well as the GameView fail to dislpay the world. When going to negative coordinates the world generation itself breaks.
There are several bugs that lead to this and they should all be fixed so that worlds can be generated, displaye and played on, independent of their origin.

**Comment by Loomie** [comment]
The problem in `MountainTopHeightMapper` is that it uses "main coordinates". So it requires 100 coordinates (2 sectors) to be available at the edge.

**Comment by Loomie** [comment]
For the game position to map coordinate conversion there seemed to be a bracketing problem. Now it is fixed.
