### ISSUE TITLE
Implement vision

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#81]
**Basic idea/big picture**
To be able to engage other elements they need to see each other. So every element (and probably other future entities, who knows) need field of vision (FOV).

**Details**
As a rather simple start every element should have the same field of vision range. It should be influenced by the surrounding terrain, especially terrain height. You just cannot look behind mountains. That means higher terrain blocks vision, when further terrain is lower.
It should suffice for the beginning when vision is "binary". An element can see a field of terrain or it can't. Maybe that is already enough and _detection_ of an enemy element present in that field is a second step affected by the enemy's state and surrounding terrain.

**Technical background**
Vision should be an attribute that can be given to any entity. The corresponding system checking the visible fields could simply "scan" all visible fields for other elements and trigger a report radio call (like "contact, unknown platoon at (x|y)/east of us").
Later this system will probably feed into the element's knowledge which other systems will use to decide what to do.

Maybe http://squidpony.github.io/SquidLib/squidlib-util/apidocs/squidpony/squidgrid/FOV.html can help with this. It should be investigated.

**Comment by Loomie** [comment]
A basic infrastructure is in place. The vision is currently determined from field to field. So elements cannot view over a valley.
