### ISSUE TITLE
Create a mechanic for how radio conversations work

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#9]
Communication via radio is rather complicated. That's why you need brevity codes and [procedure words](https://en.wikipedia.org/wiki/Procedure_word). That in turn makes radio messages easily parsable from strings (or at least I hope so...). A message translated via radio might be represented as a string containing prowords and parameters to them (like "MOVE TO (x|y)"). This string can easily be created (i.e. player sends a command) and parsed (a Unit in the field receives the message nad acts accordingly). Depending on the radio signal strength carrying the message this string might be distorted which makes parsing it harder to impossible (i.e. "M#VE TO (k|y)"). Some fuzzy string parsing magic would have to handle that but that is some future work...

This issue should lay the basics to create and parse clear messages that make up a whole conversation. The idea so far:
A `Conversation` is a consecutive sequence of `Transmissions` between two `Elements` (i.e. HQ and Alpha). Its purpose might be to submit a command (like the move command) or request a report (SITREP) or the like. A `Conversation` consists of `Parts` which might contain one or more `Transmissions`. To clarify what a `Part` is look at this example:

---- Part *init*
**HQ**: "Alpha, this is HQ, out"
**Alpha**: "HQ, come in, out"
---- Part *submit command*
**HQ**: "Alpha, move to (554|757), out"
**Alpha**: "Roger that, HQ, moving to (554|757), over"

I would like to have a nice way to define those flows of a `Conversation`, as they might take different ways when getting more complex (I don't have an example though, maybe when adding story like conversations). Maybe it might look like:
```
conversation("MoveToCommand") {
    part {
        init(receiver)
    }
    part{
        sendCommand("MoveTo", position)
        expectResponse(
                positive{
                    endConversation()
                },
                negative(
                        part {
                            ask("why")
                        }
                ))
    }
}
```
But maybe that's waaaay too complicated... Let's start with some actual commands/reports and see how it is best implemented.

**Comment by Loomie** [comment]
For military purposes there is an offical document describing radio conversations.
https://en.wikipedia.org/wiki/ACP_125
"The aim of ACP125 is to prescribe the voice procedure for use by the armed forces of Allied nations on secure and insecure tactical voice nets.  Its purpose is to provide a standardized way of passing speech and data traffic as securely as possible consistent with accuracy, speed and the needs of command and control."

It also contains a point missing so far: Security. But that is for another issue or can just be assumed to be established.
