### ISSUE TITLE
Save&Load the WorldMap

### ISSUE THREAD

**Issue by Baret** [Baret/pltcmd#96]
**Basic idea/big picture**
When developing you have to wait for the map generation every single time. It would be great if the map generated with the `DEBUG_MAP_SEED` was in a saved file in the resources folder so you can skip the generation process by simply loading it.
In the long run this feature may also be useful as the basis for savegames.

**Details**
We already have an option to quickly toggle the intro and if we want to use the debug map seed or generate a random world. I would expand this to a "dev mode" which can be enabled/disabled in the `GameOptions`. Dev mode makes the game startup quicker and sets you in a specific state that we will most probably need throughout development (like a fixed map where you know in which locations you can test stuff). So for now it would skip the intro and load the map from the file system.

The ToDos of this issue are as follows (open for discussion/change, of course):
- Create a Keybinding to save the current map to a file while in the `GameView`
  - Preferably one of the F-Keys and not F1 as it will probably be the "Help" keybinding at some point
  - The filename should not overwrite an existing file that contains a different map. So it should contain the map seed (to easily reproduce it if needed) and probably a timestamp.
- On startup load a file that is committed in `src/main/resources` when `GameOption.devMode` == `true`
- Create a Unittest that checks if the map generation with the debug seed results in the same map that is stored in `src/main/resources`
  - It should test the saving and loading (compare the newly created file with the checked in one and compare the loaded map with the generated one)
  - This helps us to recognize changes in world generation. When something changes this test should become red so we know that we need to "export" the "debug map" again and commit it.

**Technical background**
I am not yet committed on the file format. Maybe something human readable is nice but on the other hand a list of 25 million tiles in text is not quite maintanable by hand :D
First I thought of JSON but it might be too hard on the file size. Just use whatever is handy. Maybe have a look for a nice kotlin lib.

Maybe we can also create our own file format that creates a zip with every sector in a single file. It might make saving changes easier for whatever reason one might use that ^^
Or a simple height- and terrain map in one file each zipped togeter:
```
debug_map.zip (oder .pcm = pltcmd map)
  debug_map.hm (hm = heightmap)
  debug_map.tm (tm = terrainmap)
```
with the heightmap being:
```
34567
35566
44456
55566
66677
```
and the terrainmap being
```
FFFGG
FFGGH
FGMMM
HHHGG
HHFGM
```
Of course a mix of both ideas is also possible.

**Related**
Direct follow up issue: #107 😃

**Comment by Loomie** [comment]
Using [Kotlin Serialization](https://kotlinlang.org/docs/serialization.html#example-json-serialization) is pretty simple.
